# Site settings
title: Juan Carlos Farah
email: juancarlos@juancarlosfarah.com
description:    Spinning counterclockwise.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://juancarlosfarah.com" # the base hostname & protocol for your site
twitter_username: juancarlosfarah
github_username:  juancarlosfarah

# Build settings
markdown:       kramdown
highlighter:    rouge

# Collections
collections:
    menu:
        output: true
        permalink: /:path/
    writing:
        output: true

exclude: [vendor]
